name: Dev Deploy

on:
  push:
    branches: [ dev ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev build-essential python3-dev
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to dev environment
      run: |
        echo "🚀 Dev build completed successfully"
        echo "📦 Version: $(node -p "require('./package.json').version")"
        echo "🌿 Branch: dev"
        echo ""
        echo "💡 This is a development build. Full CI runs only on main branch."
        echo "📋 To release: Create a PR from dev to main"
        # Add your dev deployment logic here
        # For example: deploy to a staging server, update dev app, etc.
